### ISSUE TITLE
Code Review - Team #154

### ISSUE THREAD

**Issue by brenoxav** [gango-anan/mint-signup-page-clone#1]
You should add missing lock icons on "create account" and "sign-in" buttons and also add missing message under the phone input field.

**Comment by gango-anan** [comment]
Noted, the missing items have been added and a pull request made, awaiting approval, thanks

**Comment by brenoxav** [comment]
> Noted, the missing items have been added and a pull request made, awaiting approval, thanks

Great!
Good luck!
